/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.imcuttle.foo.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)")
public class BindExamPaperReq implements org.apache.thrift.TBase<BindExamPaperReq, BindExamPaperReq._Fields>, java.io.Serializable, Cloneable, Comparable<BindExamPaperReq> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BindExamPaperReq");

  private static final org.apache.thrift.protocol.TField TASK_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("taskId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField EXAM_PAPER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("examPaperId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField OPERATOR_USER_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("operatorUserId", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BindExamPaperReqStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BindExamPaperReqTupleSchemeFactory());
  }

  private long taskId; // required
  private long examPaperId; // required
  private int operatorUserId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TASK_ID((short)1, "taskId"),
    EXAM_PAPER_ID((short)2, "examPaperId"),
    OPERATOR_USER_ID((short)3, "operatorUserId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TASK_ID
          return TASK_ID;
        case 2: // EXAM_PAPER_ID
          return EXAM_PAPER_ID;
        case 3: // OPERATOR_USER_ID
          return OPERATOR_USER_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TASKID_ISSET_ID = 0;
  private static final int __EXAMPAPERID_ISSET_ID = 1;
  private static final int __OPERATORUSERID_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.OPERATOR_USER_ID};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TASK_ID, new org.apache.thrift.meta_data.FieldMetaData("taskId", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.EXAM_PAPER_ID, new org.apache.thrift.meta_data.FieldMetaData("examPaperId", org.apache.thrift.TFieldRequirementType.REQUIRED,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.OPERATOR_USER_ID, new org.apache.thrift.meta_data.FieldMetaData("operatorUserId", org.apache.thrift.TFieldRequirementType.OPTIONAL,
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BindExamPaperReq.class, metaDataMap);
  }

  public BindExamPaperReq() {
  }

  public BindExamPaperReq(
    long taskId,
    long examPaperId)
  {
    this();
    this.taskId = taskId;
    setTaskIdIsSet(true);
    this.examPaperId = examPaperId;
    setExamPaperIdIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BindExamPaperReq(BindExamPaperReq other) {
    __isset_bitfield = other.__isset_bitfield;
    this.taskId = other.taskId;
    this.examPaperId = other.examPaperId;
    this.operatorUserId = other.operatorUserId;
  }

  public BindExamPaperReq deepCopy() {
    return new BindExamPaperReq(this);
  }

  @Override
  public void clear() {
    setTaskIdIsSet(false);
    this.taskId = 0;
    setExamPaperIdIsSet(false);
    this.examPaperId = 0;
    setOperatorUserIdIsSet(false);
    this.operatorUserId = 0;
  }

  public long getTaskId() {
    return this.taskId;
  }

  public void setTaskId(long taskId) {
    this.taskId = taskId;
    setTaskIdIsSet(true);
  }

  public void unsetTaskId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TASKID_ISSET_ID);
  }

  /** Returns true if field taskId is set (has been assigned a value) and false otherwise */
  public boolean isSetTaskId() {
    return EncodingUtils.testBit(__isset_bitfield, __TASKID_ISSET_ID);
  }

  public void setTaskIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TASKID_ISSET_ID, value);
  }

  public long getExamPaperId() {
    return this.examPaperId;
  }

  public void setExamPaperId(long examPaperId) {
    this.examPaperId = examPaperId;
    setExamPaperIdIsSet(true);
  }

  public void unsetExamPaperId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __EXAMPAPERID_ISSET_ID);
  }

  /** Returns true if field examPaperId is set (has been assigned a value) and false otherwise */
  public boolean isSetExamPaperId() {
    return EncodingUtils.testBit(__isset_bitfield, __EXAMPAPERID_ISSET_ID);
  }

  public void setExamPaperIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __EXAMPAPERID_ISSET_ID, value);
  }

  public int getOperatorUserId() {
    return this.operatorUserId;
  }

  public void setOperatorUserId(int operatorUserId) {
    this.operatorUserId = operatorUserId;
    setOperatorUserIdIsSet(true);
  }

  public void unsetOperatorUserId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OPERATORUSERID_ISSET_ID);
  }

  /** Returns true if field operatorUserId is set (has been assigned a value) and false otherwise */
  public boolean isSetOperatorUserId() {
    return EncodingUtils.testBit(__isset_bitfield, __OPERATORUSERID_ISSET_ID);
  }

  public void setOperatorUserIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OPERATORUSERID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TASK_ID:
      if (value == null) {
        unsetTaskId();
      } else {
        setTaskId((Long)value);
      }
      break;

    case EXAM_PAPER_ID:
      if (value == null) {
        unsetExamPaperId();
      } else {
        setExamPaperId((Long)value);
      }
      break;

    case OPERATOR_USER_ID:
      if (value == null) {
        unsetOperatorUserId();
      } else {
        setOperatorUserId((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TASK_ID:
      return getTaskId();

    case EXAM_PAPER_ID:
      return getExamPaperId();

    case OPERATOR_USER_ID:
      return getOperatorUserId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TASK_ID:
      return isSetTaskId();
    case EXAM_PAPER_ID:
      return isSetExamPaperId();
    case OPERATOR_USER_ID:
      return isSetOperatorUserId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BindExamPaperReq)
      return this.equals((BindExamPaperReq)that);
    return false;
  }

  public boolean equals(BindExamPaperReq that) {
    if (that == null)
      return false;

    boolean this_present_taskId = true;
    boolean that_present_taskId = true;
    if (this_present_taskId || that_present_taskId) {
      if (!(this_present_taskId && that_present_taskId))
        return false;
      if (this.taskId != that.taskId)
        return false;
    }

    boolean this_present_examPaperId = true;
    boolean that_present_examPaperId = true;
    if (this_present_examPaperId || that_present_examPaperId) {
      if (!(this_present_examPaperId && that_present_examPaperId))
        return false;
      if (this.examPaperId != that.examPaperId)
        return false;
    }

    boolean this_present_operatorUserId = true && this.isSetOperatorUserId();
    boolean that_present_operatorUserId = true && that.isSetOperatorUserId();
    if (this_present_operatorUserId || that_present_operatorUserId) {
      if (!(this_present_operatorUserId && that_present_operatorUserId))
        return false;
      if (this.operatorUserId != that.operatorUserId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_taskId = true;
    list.add(present_taskId);
    if (present_taskId)
      list.add(taskId);

    boolean present_examPaperId = true;
    list.add(present_examPaperId);
    if (present_examPaperId)
      list.add(examPaperId);

    boolean present_operatorUserId = true && (isSetOperatorUserId());
    list.add(present_operatorUserId);
    if (present_operatorUserId)
      list.add(operatorUserId);

    return list.hashCode();
  }

  @Override
  public int compareTo(BindExamPaperReq other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTaskId()).compareTo(other.isSetTaskId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTaskId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.taskId, other.taskId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetExamPaperId()).compareTo(other.isSetExamPaperId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExamPaperId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.examPaperId, other.examPaperId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOperatorUserId()).compareTo(other.isSetOperatorUserId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperatorUserId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operatorUserId, other.operatorUserId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BindExamPaperReq(");
    boolean first = true;

    sb.append("taskId:");
    sb.append(this.taskId);
    first = false;
    if (!first) sb.append(", ");
    sb.append("examPaperId:");
    sb.append(this.examPaperId);
    first = false;
    if (isSetOperatorUserId()) {
      if (!first) sb.append(", ");
      sb.append("operatorUserId:");
      sb.append(this.operatorUserId);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!isSetTaskId()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'taskId' is unset! Struct:" + toString());
    }

    if (!isSetExamPaperId()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'examPaperId' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BindExamPaperReqStandardSchemeFactory implements SchemeFactory {
    public BindExamPaperReqStandardScheme getScheme() {
      return new BindExamPaperReqStandardScheme();
    }
  }

  private static class BindExamPaperReqStandardScheme extends StandardScheme<BindExamPaperReq> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BindExamPaperReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) {
          break;
        }
        switch (schemeField.id) {
          case 1: // TASK_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.taskId = iprot.readI64();
              struct.setTaskIdIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EXAM_PAPER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.examPaperId = iprot.readI64();
              struct.setExamPaperIdIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // OPERATOR_USER_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.operatorUserId = iprot.readI32();
              struct.setOperatorUserIdIsSet(true);
            } else {
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BindExamPaperReq struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(TASK_ID_FIELD_DESC);
      oprot.writeI64(struct.taskId);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(EXAM_PAPER_ID_FIELD_DESC);
      oprot.writeI64(struct.examPaperId);
      oprot.writeFieldEnd();
      if (struct.isSetOperatorUserId()) {
        oprot.writeFieldBegin(OPERATOR_USER_ID_FIELD_DESC);
        oprot.writeI32(struct.operatorUserId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BindExamPaperReqTupleSchemeFactory implements SchemeFactory {
    public BindExamPaperReqTupleScheme getScheme() {
      return new BindExamPaperReqTupleScheme();
    }
  }

  private static class BindExamPaperReqTupleScheme extends TupleScheme<BindExamPaperReq> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BindExamPaperReq struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI64(struct.taskId);
      oprot.writeI64(struct.examPaperId);
      BitSet optionals = new BitSet();
      if (struct.isSetOperatorUserId()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetOperatorUserId()) {
        oprot.writeI32(struct.operatorUserId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BindExamPaperReq struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.taskId = iprot.readI64();
      struct.setTaskIdIsSet(true);
      struct.examPaperId = iprot.readI64();
      struct.setExamPaperIdIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.operatorUserId = iprot.readI32();
        struct.setOperatorUserIdIsSet(true);
      }
    }
  }

}

